all:
  hosts:
    master: &id001
      ansible_host: 84.201.134.219
      ip: 10.10.0.9
      access_ip: 10.10.0.9
      ansible_user: ubuntu
      routes_to_add:
      - to: 10.20.0.0/24
        via: 10.20.0.1
      - to: 10.30.0.0/24
        via: 10.30.0.1
      subnet: 10.10.0.0/24
      ansible_ssh_common_args: ''
    worker1: &id002
      ansible_host: 158.160.16.29
      ip: 10.20.0.24
      access_ip: 10.20.0.24
      ansible_user: ubuntu
      routes_to_add:
      - to: 10.10.0.0/24
        via: 10.10.0.1
      - to: 10.30.0.0/24
        via: 10.30.0.1
      subnet: 10.20.0.0/24
    worker2: &id003
      ansible_host: 130.193.57.203
      ip: 10.30.0.25
      access_ip: 10.30.0.25
      ansible_user: ubuntu
      routes_to_add:
      - to: 10.10.0.0/24
        via: 10.10.0.1
      - to: 10.20.0.0/24
        via: 10.20.0.1
      subnet: 10.30.0.0/24
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kube_network_plugin: calico
    ansible_become: true
    public_api_ip: 84.201.134.219
    loadbalancer_apiserver:
      address: 84.201.134.219
      port: 6443
    kubeadm_config_api_fqdn: 84.201.134.219
    control_plane_endpoint: 84.201.134.219:6443
    kubeadm_init_retry_timeout: 600
  children:
    kube_control_plane:
      hosts:
        master: *id001
    kube_node:
      hosts:
        worker1: *id002
        worker2: *id003
    etcd:
      hosts:
        master: *id001
    k8s_cluster:
      children:
        kube_control_plane: {}
        kube_node: {}
    calico_rr:
      hosts: {}
