kube_version: v1.30.0
kube_network_plugin: calico
kube_proxy_mode: ipvs

apiserver_loadbalancer_domain_name: "kubernetes"
loadbalancer_apiserver:
  address: "{{ public_api_ip }}"
  port: 6443

kubeconfig_localhost: true
