---
- name: Fix KUBECONFIG to use local SSH tunnel
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"

  tasks:
    - name: Checking existence of kubeconfig
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_stat

    - name: Error if not exists
      fail:
        msg: "Kubeconfig file {{ kubeconfig_path }} not found!"
      when: not kubeconfig_stat.stat.exists

    - name: Replacing API address with local tunnel in kubeconfig
      ansible.builtin.replace:
        path: "{{ kubeconfig_path }}"
        regexp: 'https://.*:[0-9]+'
        replace: "https://127.0.0.1:{{ master_port | default(16443) }}"

    - name: Updated API address
      shell: "grep 'server:' {{ kubeconfig_path }}"
      register: server_line
      changed_when: false

    - debug:
        msg: "API server in kubeconfig set to {{ server_line.stdout }}"
