---
- name: Update kubeconfig with actual master IP
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    kubeconfig_path: "{{ playbook_dir }}/../inventory/mycluster/artifacts/admin.conf"
    master_ip: "{{ master_ip }}"

  tasks:
    - name: Replace server address in kubeconfig
      replace:
        path: "{{ kubeconfig_path }}"
        regexp: 'server: https://.*:6443'
        replace: "server: https://{{ master_ip }}:6443"

    - name: Ensure KUBECONFIG is exported in bashrc
      lineinfile:
        path: "~/.bashrc"
        line: "export KUBECONFIG={{ kubeconfig_path }}"
        state: present
