---
- name: Set KUBECONFIG on master node
  hosts: kube_control_plane
  become: true

  tasks:
    - name: Add KUBECONFIG to /etc/environment
      lineinfile:
        path: /etc/environment
        line: 'KUBECONFIG=/etc/kubernetes/admin.conf'
        state: present

    - name: Export KUBECONFIG in .bashrc for interactive sessions
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
        create: yes
        state: present
      become: false

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0700'
        owner: ubuntu
        group: ubuntu

    - name: Copy admin.conf to ubuntu kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'
        remote_src: true
