---
- hosts: all
  become: true
  tasks:
    - name: Disable swap
      command: swapoff -a

    - name: Remove swap entry from fstab
      replace:
        path: /etc/fstab
        regexp: '^(\S+\s+\S+\s+swap\s+.*)$'
        replace: '# \1'
