---
- name: Install Kubernetes tools (kubeadm, kubelet, kubectl)
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Kubernetes apt GPG key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key \
        | gpg --dearmor --batch --yes -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
      args:
        executable: /bin/bash

    - name: Add Kubernetes apt repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
      notify:
        - apt update

    - name: Install kubelet, kubeadm and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubelet kubeadm kubectl versions
      ansible.builtin.shell: |
        apt-mark hold kubelet kubeadm kubectl

  handlers:
    - name: apt update
      apt:
        update_cache: yes
