---
- name: Reset Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Stop kubelet
      systemd:
        name: kubelet
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Reset kubeadm
      command: kubeadm reset -f
      ignore_errors: true

    - name: Remove Kubernetes dirs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/etcd
        - /var/lib/kubelet
        - /var/lib/cni
        - /run/kubernetes

    - name: Swapoff
      command: swapoff -a
      ignore_errors: true

    - name: Correct /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].* swap .*)$'
        replace: '#\\1'

    - name: Ensure kubelet started
      systemd:
        name: kubelet
        state: started
        enabled: yes
      ignore_errors: true

